# Generated by Django 4.0.4 on 2022-05-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time',
            new_name='servings',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time_unit',
            new_name='servings_unit',
        ),
    ]
